### ISSUE TITLE
please, check switch case way, maybe it will be better than if else

### ISSUE THREAD

**Issue by Yurii-Chaban** [AlexTereschenko/Herogotchi#10]
https://github.com/AlexTereschenko/Herogotchi/blob/27084cad4cc732de1899c04eb678c7cfa1d07d67/js/script.js#L355

**Comment by AlexTereschenko** [comment]
What should it looks like, what to transfer to the switch? switch(this)?? there are 5 different checks, and as far as I know, in the switch, one argument is checked for different values

**Comment by Yurii-Chaban** [comment]
agree with you
