### ISSUE TITLE
it shoul be button but not span as a button

### ISSUE THREAD

**Issue by Yurii-Chaban** [AlexTereschenko/Herogotchi#2]
https://github.com/AlexTereschenko/Herogotchi/blob/27084cad4cc732de1899c04eb678c7cfa1d07d67/index.html#L25

**Comment by AlexTereschenko** [comment]
`<button class="btn btn__add js-btn__add"><span class="material-symbols-outlined icon unselectable">person_add</span></button>`

changed all to buttons, but Idk why was it a mistake. I very often see buttons in the form of a logo or even a picture.

**Comment by Yurii-Chaban** [comment]
because each HTML tag has to perform its own functionality, which is embedded in it
