### ISSUE TITLE
What the class="main" mean? It should be readable class to have some logic to understanding like "heroes-container" or just "heroes" and article should be just "hero" class but not "heroes"

### ISSUE THREAD

**Issue by Yurii-Chaban** [AlexTereschenko/Herogotchi#3]
https://github.com/AlexTereschenko/Herogotchi/blob/27084cad4cc732de1899c04eb678c7cfa1d07d67/index.html#LL31C15-L31C27

**Comment by AlexTereschenko** [comment]
get it, just deleted it because it wasn't even used. 
Sometimes I just add classes upfront that might come in handy. I've used the selectors itself before for some point edits, but either you or the mentor said never ever to use a bare tags, so I have to sketch ahead where I think it will be needed

**Comment by Yurii-Chaban** [comment]
KISS, DRY or okama
