### ISSUE TITLE
better to move this array of objects to separate file and make JSON structure, and parse JSON in script.js

### ISSUE THREAD

**Issue by Yurii-Chaban** [AlexTereschenko/Herogotchi#4]
https://github.com/AlexTereschenko/Herogotchi/blob/27084cad4cc732de1899c04eb678c7cfa1d07d67/js/script.js#L1

**Comment by AlexTereschenko** [comment]
have a problem with that
`const request = new XMLHttpRequest();
request.open("GET", '../data/names.json', false);
request.send(null);
request.onreadystatechange = function() {
  if ( request.readyState === 4 && request.status === 200 ) {
    const my_JSON_object = JSON.parse(request.responseText);
    console.log(my_JSON_object);
  }
}`
And get 404 (Not Found)
