### ISSUE TITLE
also you don't need ELSE as you done the same logic for this.refreshStatus(stats, btns);, you just need only IF

### ISSUE THREAD

**Issue by Yurii-Chaban** [AlexTereschenko/Herogotchi#9]
https://github.com/AlexTereschenko/Herogotchi/blob/27084cad4cc732de1899c04eb678c7cfa1d07d67/js/script.js#L220

**Comment by AlexTereschenko** [comment]
Ok if I have enough money, i'll do logic and at the end I once refreshStatus() whatever I have money or not. Get it
